# Generated by Django 2.1.7 on 2019-10-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arithmetic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='rule_name',
            field=models.CharField(default='0', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rule',
            name='rule_text',
            field=models.CharField(max_length=200),
        ),
    ]
