# Generated by Django 2.1.7 on 2020-01-31 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arithmetic', '0004_questionwithselection_qws_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_number', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='questionwithselection',
            name='QWS_subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='arithmetic.Subject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionwithselection',
            name='QWS_text',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='selection',
            name='selection_text',
            field=models.CharField(max_length=150),
        ),
    ]
