# Generated by Django 2.1.7 on 2020-01-31 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arithmetic', '0005_auto_20200131_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionwithselection',
            name='QWS_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='arithmetic.Year'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rule',
            name='year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='arithmetic.Year'),
            preserve_default=False,
        ),
    ]
